name: InternalModules
version: "2020.07.26"
license: "GPL-2.0-or-later"
date: 2020-07-26
description: |
    Modules over internal algebras

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Fabian Zickgraf
      url: https://algebra.mathematik.uni-siegen.de/zickgraf

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Fabian Zickgraf
      url: https://algebra.mathematik.uni-siegen.de/zickgraf

GAP: ">= 4.9.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "GradedCategories"
      version: ">= 2020.07.24"
      url: "https://github.com/homalg-project/GradedCategories"
    - name: "ActionsForCAP"
      version: ">= 2020.04.27"
      url: "http://homalg-project.github.io/CAP_project/"

www: https://homalg-project.github.io/InternalModules
readme: README.md
packageinfo: https://homalg-project.github.io/InternalModules/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/InternalModules/releases/download/v2020.07.26/InternalModules-2020.07.26.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    internalized algebras, modules over internalized algebras, internalized symmetric algebra.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BZ20</span>]   <b class='BibAuthor'>Barakat, M. and Zickgraf, F.</b>,
     <i class='BibTitle'>InternalModules, Modules over internal algebras,
             Version 2020.07.26</i>
     (<span class='BibYear'>2020</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/InternalModules">https://homalg-project.github.io/InternalModules</a></span>.
    </p>
    

bibtex: |
    @misc{ InternalModules2020.07.26,
      author =           {Barakat, M. and Zickgraf, F.},
      title =            {{InternalModules}, Modules over internal algebras, {V}ersion 2020.07.26},
      month =            {Jul},
      year =             {2020},
      note =             {GAP package},
      howpublished =     {\href {https://homalg-project.github.io/InternalModules} {\texttt{https://homalg-project.github.io/}\discretionary {}{}{}\texttt{InternalModules}}},
      keywords =         {internalized algebras, modules over internalized algebras, internalized symmetric algebra},
      printedkey =       {BZ20}
    }

