name: InternalModules
version: "2022.06-02"
license: "GPL-2.0-or-later"
date: 2022-06-29
description: |
    Modules over internal algebras

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Fabian Zickgraf
      url: https://algebra.mathematik.uni-siegen.de/zickgraf

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Fabian Zickgraf
      url: https://algebra.mathematik.uni-siegen.de/zickgraf

GAP: ">= 4.11.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "GradedCategories"
      version: ">= 2020.08.24"
      url: "https://homalg-project.github.io/pkg/GradedCategories"
    - name: "ActionsForCAP"
      version: ">= 2020.04.27"
      url: "https://homalg-project.github.io/pkg/ActionsForCAP"
    - name: "RingsForHomalg"
      version: ">= 2020.09.02"
      url: "https://homalg-project.github.io/pkg/RingsForHomalg"
    - name: "MatricesForHomalg"
      version: ">= 2022.06-01"
      url: "https://homalg-project.github.io/pkg/MatricesForHomalg"
    - name: "ToolsForHomalg"
      version: ">= 2020.09.01"
      url: "https://homalg-project.github.io/pkg/ToolsForHomalg"

www: https://homalg-project.github.io/pkg/InternalModules
readme: README.md
packageinfo: https://homalg-project.github.io/InternalModules/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/InternalModules/releases/download/v2022.06-02/InternalModules-2022.06-02.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/InternalModules/releases/download/v2022.06-02/InternalModules-2022.06-02.zip

pdf: https://github.com/homalg-project/InternalModules/releases/download/v2022.06-02/InternalModules-2022.06-02.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    internalized algebras, modules over internalized algebras, internalized symmetric algebra.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BZ22</span>]   <b class='BibAuthor'>Barakat, M. and Zickgraf, F.</b>,
     <i class='BibTitle'>InternalModules, Modules over internal algebras,
             Version 2022.06-02</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/pkg/InternalModules">https://homalg-project.github.io/pkg/InternalModules</a></span>.
    </p>
    

bibtex: |
    @misc{ InternalModules2022.06-02,
      author =           {Barakat, M. and Zickgraf, F.},
      title =            {{InternalModules},  Modules  over  internal  algebras,
                          {V}ersion 2022.06-02},
      month =            {Jun},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/pkg/InternalModules}
                          {\texttt{https://homalg-project.github.io/}\discretionary
                          {}{}{}\texttt{pkg/}\discretionary
                          {}{}{}\texttt{InternalModules}}},
      keywords =         {internalized   algebras,   modules  over  internalized
                          algebras, internalized symmetric algebra},
      printedkey =       {BZ22}
    }

